#!/usr/bin/env python3
from prettytable import PrettyTable
from pelotondatabase import get_ride_output,get_user_id,get_following

x = PrettyTable()
x.field_names = ['start time','name','duration','total work','title','original air time']
for ride in get_ride_output(get_user_id()):
    x.add_row(ride)
print(x)

x = PrettyTable()
x.field_names = ['username','id']
for user in get_following(get_user_id()):
    x.add_row(user)
print(x)
